<a href="https://colab.research.google.com/github/A1Analytics/-A1-Analytics-Data_Analytics_Project01/blob/main/Project_01_Salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Simple Linear Regression

In [2]:
#Step01 import
import pandas as pd

######PASTED THE URL AND CHANGED BLOB TO RAW
https://github.com/YBIFoundation/Dataset/blob/main/Salary%20Data.csv

https://github.com/YBIFoundation/Dataset/raw/main/Salary%20Data.csv

In [3]:
#Step02 Read Data set
df=pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Salary%20Data.csv')

###### **now run df.head(), df.info(), df.describe()**

In [4]:
df.head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 772.0 bytes

In [6]:
df.describe()

       Experience Years         Salary
count         40.000000      40.000000
mean           5.152500   74743.625000
std            2.663715   25947.122885
min            1.100000   37731.000000
25%            3.200000   56878.250000
50%            4.600000   64472.500000
75%            6.875000   95023.250000
max           10.500000  122391.000000

In [7]:
#Step03 Define the input and output
df.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [8]:
x=df[['Experience Years']]
y=df['Salary']

In [9]:
#Step04 Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=2)

In [10]:
#Step05 Select Model
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [11]:
#Step06 Train Model
model.fit(x_train,y_train)

LinearRegression()

In [12]:
#Step07 Test and Prediction
y_pred=model.predict(x_test)

In [13]:
#Step08 Evaluation
from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error,mean_squared_error
mean_absolute_percentage_error(y_test,y_pred)

0.06485440905142517

now multiply it with 100 0.06 x 100 = 6.48%

In [14]:
import joblib
joblib.dump(model,'salary.p1')

['salary.p1']

In [15]:
from google.colab import files
files.download('salary.p1')